### PR TITLE
Fix for Issue 130, updated gt, gte, lt, lte comparison methods

### PR DESCRIPTION
**Pull request by cognitiveflux**
Addresses issue #130

### CODE REVIEW

**Comment by cognitiveflux** [comment]
Build test failing due to a bundler issue, please restart; tests pass locally.

**Comment by sxross** [comment]
This failure on Travis happens occasionally ... well, more than occasionally ... and I'm not sure why:

```
$ bundle exec rake spec
Could not find rake-10.1.0 in any of the sources
Run `bundle install` to install missing gems.
```

The gemfile reveals that no version is specified for rake. Any idea why the sporadic failures? I'd like to get a Travis green light on this one.

**Comment by cognitiveflux** [comment]
I'm not sure what's going on with Travis, the same error was reported in the previous pull request I submitted ( #124 ), [but it passed](https://travis-ci.org/sxross/MotionModel/builds/40130475).  I have yet to find one community project that doesn't have consistent issues with Travis CI.

The `Gemfile.lock` file has `10.1.0` specified, but in the test history for Travis it says that bundler installed rake correctly.  Would you please try restarting the job?

If I had to guess it would be something with the bundler path, but I'm not familiar enough with Travis to troubleshoot it further.

**Comment by cognitiveflux** [comment]
Looking around the [Travis issues](https://github.com/travis-ci/travis-ci/issues/2253), have you tried this in the `.travis.yml`?:

`install: ruby -S bundle install`

**Comment by cognitiveflux** [comment]
Noticed your recent commits, have you tried mirroring the `BubbleWrap` travis config?

```yaml
language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
script:
    - bundle install
    - bundle exec rake clean
    - bundle exec rake spec
    - bundle exec rake clean
    - bundle exec rake spec osx=true
```

Then again, `BW` has been having build issues with Travis for eons.

**Comment by sxross** [comment]
I think it’s a problem with RubyMotion. In RubyMotion/lib/motion/util/version.rb, the version is compared against a non-empty regular expression. What version? I don’t know. RubyMotion version? App version? SDK version? Anyhow, that’s what’s failing now, so I filed a motion support issue.

Let’s see what @eloy has to say...

**Comment by sxross** [comment]
Passes local tests. Should pass Travis with new travis.yml I just (finally) figured out.

**Pull request merged**
