### PR TITLE
Adds spec testing correct IDs after deserialization along with dat file ...

### PR DESCRIPTION
**Pull request by digitalfx**
...to test against.

### CODE REVIEW

**Comment by digitalfx** [comment]
Is this correct? Still looks like it wants to go to master to me :confounded:

**Comment by digitalfx** [comment]
Do let me know if there's anything else I can do to assist :)

**Comment by sxross** [comment]
I'm just happy you're looking at this stuff! If you want to look at the code, the stuff that deserializes is in array_model_persistance.rb but what's probably to blame here is in array_model_adapter.rb, where `_next_id` is being given out. For some reason, in a freshly deserialized data store, `_next_id` assumes the maximum of all previously allocated id's. It should assume the max+1. I'm not yet seeing why this isn't the case. If you want to take a look at it, that would be incredible.

**Comment by digitalfx** [comment]
Just added https://github.com/digitalfx/MotionModel/commit/f1e42623de5817b4807953ba91c0ab11af1ed34f which fixes the bug. It's not necessarily the most elegant solution as this waits until after deserialization to fix the problem, but it appears to work.

**Comment by digitalfx** [comment]
Awesome, thanks for merging and version bumping :)

**Pull request merged**
