### PR TITLE
Adds #array method as alias of #all

### PR DESCRIPTION
**Pull request by digitalfx**
Just a small syntax addition that I got used to with CDQ, and makes more sense in my head. Clearly indicates that it's casting from a MM object type to an array, and reads better (to me) with queries e.g.
`Task.where(:importance).gt(2).all` becomes `Task.where(:importance).gt(2).array`

### CODE REVIEW

**Comment by sxross** [comment]
Travis is failing on this change. I have no idea why. Pursuing it now.

**Comment by sxross** [comment]
Please catch up to master and your Travis build should pass. Then I can merge.

**Comment by digitalfx** [comment]
All done :grin

**Comment by sxross** [comment]
Thanks!

**Comment by digitalfx** [comment]
👍

**Comment by digitalfx** [comment]
Hold on, has this been closed and not merged? (can't tell properly as I'm on mobile).

**Pull request merged**
