### PR TITLE
Spec covering duplicate IDs after quit and relaunch

### PR DESCRIPTION
**Pull request by digitalfx**
Covers #135 I believe.

### CODE REVIEW

**Comment by sxross** [comment]
Can you please move that to a different branch so I don't disturb master?

Thanks!

**Comment by digitalfx** [comment]
Yep sure

**Comment by digitalfx** [comment]
Ummm.... how do I do that. I have created a new branch on my fork, but when I come to make the PR I can't use that branch on this repo?

**Comment by sxross** [comment]
git push -b

That always works for me.

**Comment by sxross** [comment]
Does this help? https://help.github.com/articles/using-pull-requests/

**Pull request closed without merging**
