### PR TITLE
Add support for different primary_key in belongs_to associations

### PR DESCRIPTION
**Pull request by awernick**
Just like the title says.

I had to modify the code to work in one of my projects, but I think it would be helpful to others if this feature was included.

### CODE REVIEW

**Comment by sxross** [comment]
Thanks for the contribution. It should be valuable.

It would be great if there were a spec and a README entry. Any chance of doing that?

**Comment by awernick** [comment]
@sxross sure thing! Let me write it and I'll update my pull request :+1:

**Comment by awernick** [comment]
@sxross I updated the README to include the necessary information. I'm not too sure about the formatting though. Is there any specific way you like to organize the README?

**Comment by sxross** [comment]
The README looks good. If you could add some examples to `spec/relation_spec.rb` that we can use to assure ourselves everything is working properly, that would be great. You have the framework for that in your README example of using a foreign key.

**Pull request closed without merging**
